### PR TITLE
fix motion launch

### PR DESCRIPTION
**Pull request by SammyRamone**
## Necessary checks
- [ ] Update package version
- [ ] Run `catkin build`
- [ ] Write documentation
- [ ] Create issues for future work
- [ ] Test on your machine
- [ ] Test on the robot
- [ ] Put the PR on our Project board

### CODE REVIEW

**Comment by Flova** [comment]
What is the benefit of wrapping the includes in the group tags?

**Comment by SammyRamone** [comment]
> What is the benefit of wrapping the includes in the group tags?

The benefit is that ROS2 will not throw an error. Out of some reason it is required in ROS2

**Comment by Flova** [comment]
Ah okay I thought I already used them with out it but I could be wrong.

**Comment by SammyRamone** [comment]
> Ah okay I thought I already used them with out it but I could be wrong.

I looked it up, you are right. It is not necessary anymore. Maybe I read an old tutorial at some point. I will change it

**Review by jaagut — APPROVED** [review]

**Pull request merged**
